#
# このファイルは、GNUInstallDirsのフォルダレイアウトをアレンジしたものです。
#
include(GNUInstallDirs)

# Debianパッケージのインストールプレフィックス(dbkg -c で参照可能)
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr" CACHE PATH "default install path" FORCE)
set(CMAKE_INSTALL_PREFIX           "/usr" CACHE PATH "default install path" FORCE)

message(STATUS "===========================================================")
message(STATUS "CMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}")
message(STATUS "CMAKE_INSTALL_SBINDIR=${CMAKE_INSTALL_SBINDIR}")
message(STATUS "CMAKE_INSTALL_LIBEXECDIR=${CMAKE_INSTALL_LIBEXECDIR}")
message(STATUS "CMAKE_INSTALL_SYSCONFDIR=${CMAKE_INSTALL_SYSCONFDIR}")
message(STATUS "CMAKE_INSTALL_SHAREDSTATEDIR=${CMAKE_INSTALL_SHAREDSTATEDIR}")
message(STATUS "CMAKE_INSTALL_LOCALSTATEDIR=${CMAKE_INSTALL_LOCALSTATEDIR}")
message(STATUS "CMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}")
message(STATUS "CMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}")
message(STATUS "CMAKE_INSTALL_OLDINCLUDEDIR=${CMAKE_INSTALL_OLDINCLUDEDIR}")
message(STATUS "CMAKE_INSTALL_DATAROOTDIR=${CMAKE_INSTALL_DATAROOTDIR}")
message(STATUS "CMAKE_INSTALL_DATADIR=${CMAKE_INSTALL_DATADIR}")
message(STATUS "CMAKE_INSTALL_INFODIR=${CMAKE_INSTALL_INFODIR}")
message(STATUS "CMAKE_INSTALL_LOCALEDIR=${CMAKE_INSTALL_LOCALEDIR}")
message(STATUS "CMAKE_INSTALL_MANDIR=${CMAKE_INSTALL_MANDIR}")
message(STATUS "CMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}")
message(STATUS "===========================================================")
